### ISSUE TITLE
JWT那个，403了。。。不知道啥原因

### ISSUE THREAD

**Issue by dawnlyn** [bingbing-gui/Asp.Net-Core-Skill#8]
![image](https://github.com/bingbing-gui/Asp.Net-Core-Skill/assets/37390307/4da6fd63-0cd9-4f8e-9237-c10de2d647c7)
一开始放到新建的8.0项目，使用apifox也这样，后面clone了项目后把这个项目加入其他解决方案后直接运行也是这样.....

希望能在公众号上讲讲8.0的WebAPI和JWT的系列文章，怎么用之类的

**Comment by bingbing-gui** [comment]
@Violet-VE  后期会有，请你这个执行的是哪个Project？
